#!/bin/sh
set -e
deno lint
echo "-------------------------------no lint issue---------------------------------"

echo "------------------------tests-------------------------------"
deno test --coverage --clean
echo "--------------------------------every tests passed--------------------------------"

deno run -A jsr:@ashishkujoy/deno-coverage-checker@0.0.7
echo "---------------------------------test coverage covers the threshold---------------------------------"