import { Feature, Tile } from "../models.ts";

export const generateTiles = (): Tile[] => [
  {
    id: "1",
    orientation: 0,
    hasShield: true,
    tileEdges: [Feature.CITY, Feature.CITY, Feature.CITY, Feature.CITY],
    tileCenter: Feature.CITY,
    tileID: "1",
  },
  {
    id: "2",
    orientation: 0,
    hasShield: true,
    tileEdges: [Feature.CITY, Feature.CITY, Feature.CITY, Feature.FIELD],
    tileCenter: Feature.CITY,
    tileID: "2",
  },
  {
    id: "3",
    orientation: 0,
    hasShield: false,
    tileEdges: [Feature.CITY, Feature.CITY, Feature.CITY, Feature.FIELD],
    tileCenter: Feature.CITY,
    tileID: "3",
  },
  {
    id: "3",
    orientation: 0,
    hasShield: false,
    tileEdges: [Feature.CITY, Feature.CITY, Feature.CITY, Feature.FIELD],
    tileCenter: Feature.CITY,
    tileID: "4",
  },
  {
    id: "3",
    orientation: 0,
    hasShield: false,
    tileEdges: [Feature.CITY, Feature.CITY, Feature.CITY, Feature.FIELD],
    tileCenter: Feature.CITY,
    tileID: "5",
  },
  {
    id: "4",
    orientation: 0,
    hasShield: true,
    tileEdges: [Feature.CITY, Feature.CITY, Feature.CITY, Feature.ROAD],
    tileCenter: Feature.CITY,
    tileID: "6",
  },
  {
    id: "4",
    orientation: 0,
    hasShield: true,
    tileEdges: [Feature.CITY, Feature.CITY, Feature.CITY, Feature.ROAD],
    tileCenter: Feature.CITY,
    tileID: "7",
  },
  {
    id: "5",
    orientation: 0,
    hasShield: false,
    tileEdges: [Feature.CITY, Feature.CITY, Feature.CITY, Feature.ROAD],
    tileCenter: Feature.CITY,
    tileID: "8",
  },
  {
    id: "6",
    orientation: 0,
    hasShield: false,
    tileEdges: [Feature.CITY, Feature.CITY, Feature.FIELD, Feature.FIELD],
    tileCenter: Feature.FIELD,
    tileID: "9",
  },
  {
    id: "6",
    orientation: 0,
    hasShield: false,
    tileEdges: [Feature.CITY, Feature.CITY, Feature.FIELD, Feature.FIELD],
    tileCenter: Feature.FIELD,
    tileID: "10",
  },
  {
    id: "7",
    orientation: 0,
    hasShield: true,
    tileEdges: [Feature.CITY, Feature.CITY, Feature.ROAD, Feature.ROAD],
    tileCenter: Feature.CITY,
    tileID: "11",
  },
  {
    id: "7",
    orientation: 0,
    hasShield: true,
    tileEdges: [Feature.CITY, Feature.CITY, Feature.ROAD, Feature.ROAD],
    tileCenter: Feature.CITY,
    tileID: "12",
  },
  {
    id: "8",
    orientation: 0,
    hasShield: false,
    tileEdges: [Feature.CITY, Feature.CITY, Feature.ROAD, Feature.ROAD],
    tileCenter: Feature.CITY,
    tileID: "13",
  },
  {
    id: "8",
    orientation: 0,
    hasShield: false,
    tileEdges: [Feature.CITY, Feature.CITY, Feature.ROAD, Feature.ROAD],
    tileCenter: Feature.CITY,
    tileID: "14",
  },
  {
    id: "8",
    orientation: 0,
    hasShield: false,
    tileEdges: [Feature.CITY, Feature.CITY, Feature.ROAD, Feature.ROAD],
    tileCenter: Feature.CITY,
    tileID: "15",
  },
  {
    id: "9",
    orientation: 0,
    hasShield: true,
    tileEdges: [Feature.CITY, Feature.FIELD, Feature.CITY, Feature.FIELD],
    tileCenter: Feature.CITY,
    tileID: "16",
  },
  {
    id: "9",
    orientation: 0,
    hasShield: true,
    tileEdges: [Feature.CITY, Feature.FIELD, Feature.CITY, Feature.FIELD],
    tileCenter: Feature.CITY,
    tileID: "17",
  },
  {
    id: "10",
    orientation: 0,
    hasShield: false,
    tileEdges: [Feature.CITY, Feature.FIELD, Feature.CITY, Feature.FIELD],
    tileCenter: Feature.CITY,
    tileID: "18",
  },
  {
    id: "11",
    orientation: 0,
    hasShield: true,
    tileEdges: [Feature.FIELD, Feature.CITY, Feature.CITY, Feature.FIELD],
    tileCenter: Feature.CITY,
    tileID: "19",
  },
  {
    id: "11",
    orientation: 0,
    hasShield: true,
    tileEdges: [Feature.FIELD, Feature.CITY, Feature.CITY, Feature.FIELD],
    tileCenter: Feature.CITY,
    tileID: "20",
  },
  {
    id: "12",
    orientation: 0,
    hasShield: false,
    tileEdges: [Feature.FIELD, Feature.CITY, Feature.CITY, Feature.FIELD],
    tileCenter: Feature.CITY,
    tileID: "21",
  },
  {
    id: "12",
    orientation: 0,
    hasShield: false,
    tileEdges: [Feature.FIELD, Feature.CITY, Feature.CITY, Feature.FIELD],
    tileCenter: Feature.CITY,
    tileID: "22",
  },
  {
    id: "12",
    orientation: 0,
    hasShield: false,
    tileEdges: [Feature.FIELD, Feature.CITY, Feature.CITY, Feature.FIELD],
    tileCenter: Feature.CITY,
    tileID: "23",
  },
  {
    id: "13",
    orientation: 0,
    hasShield: false,
    tileEdges: [Feature.FIELD, Feature.CITY, Feature.FIELD, Feature.CITY],
    tileCenter: Feature.FIELD,
    tileID: "24",
  },
  {
    id: "13",
    orientation: 0,
    hasShield: false,
    tileEdges: [Feature.FIELD, Feature.CITY, Feature.FIELD, Feature.CITY],
    tileCenter: Feature.FIELD,
    tileID: "25",
  },
  {
    id: "13",
    orientation: 0,
    hasShield: false,
    tileEdges: [Feature.FIELD, Feature.CITY, Feature.FIELD, Feature.CITY],
    tileCenter: Feature.FIELD,
    tileID: "26",
  },
  {
    id: "14",
    orientation: 0,
    hasShield: false,
    tileEdges: [Feature.FIELD, Feature.CITY, Feature.FIELD, Feature.FIELD],
    tileCenter: Feature.FIELD,
    tileID: "27",
  },
  {
    id: "14",
    orientation: 0,
    hasShield: false,
    tileEdges: [Feature.FIELD, Feature.CITY, Feature.FIELD, Feature.FIELD],
    tileCenter: Feature.FIELD,
    tileID: "28",
  },
  {
    id: "14",
    orientation: 0,
    hasShield: false,
    tileEdges: [Feature.FIELD, Feature.CITY, Feature.FIELD, Feature.FIELD],
    tileCenter: Feature.FIELD,
    tileID: "29",
  },
  {
    id: "14",
    orientation: 0,
    hasShield: false,
    tileEdges: [Feature.FIELD, Feature.CITY, Feature.FIELD, Feature.FIELD],
    tileCenter: Feature.FIELD,
    tileID: "30",
  },
  {
    id: "14",
    orientation: 0,
    hasShield: false,
    tileEdges: [Feature.FIELD, Feature.CITY, Feature.FIELD, Feature.FIELD],
    tileCenter: Feature.FIELD,
    tileID: "31",
  },
  {
    id: "15",
    orientation: 0,
    hasShield: false,
    tileEdges: [Feature.FIELD, Feature.CITY, Feature.ROAD, Feature.ROAD],
    tileCenter: Feature.ROAD,
    tileID: "32",
  },
  {
    id: "15",
    orientation: 0,
    hasShield: false,
    tileEdges: [Feature.FIELD, Feature.CITY, Feature.ROAD, Feature.ROAD],
    tileCenter: Feature.ROAD,
    tileID: "33",
  },
  {
    id: "15",
    orientation: 0,
    hasShield: false,
    tileEdges: [Feature.FIELD, Feature.CITY, Feature.ROAD, Feature.ROAD],
    tileCenter: Feature.ROAD,
    tileID: "34",
  },
  {
    id: "16",
    orientation: 0,
    hasShield: false,
    tileEdges: [Feature.FIELD, Feature.FIELD, Feature.FIELD, Feature.FIELD],
    tileCenter: Feature.MONASTERY,
    tileID: "35",
  },
  {
    id: "16",
    orientation: 0,
    hasShield: false,
    tileEdges: [Feature.FIELD, Feature.FIELD, Feature.FIELD, Feature.FIELD],
    tileCenter: Feature.MONASTERY,
    tileID: "36",
  },
  {
    id: "16",
    orientation: 0,
    hasShield: false,
    tileEdges: [Feature.FIELD, Feature.FIELD, Feature.FIELD, Feature.FIELD],
    tileCenter: Feature.MONASTERY,
    tileID: "37",
  },
  {
    id: "16",
    orientation: 0,
    hasShield: false,
    tileEdges: [Feature.FIELD, Feature.FIELD, Feature.FIELD, Feature.FIELD],
    tileCenter: Feature.MONASTERY,
    tileID: "38",
  },
  {
    id: "17",
    orientation: 0,
    hasShield: false,
    tileEdges: [Feature.FIELD, Feature.FIELD, Feature.FIELD, Feature.ROAD],
    tileCenter: Feature.MONASTERY,
    tileID: "39",
  },
  {
    id: "17",
    orientation: 0,
    hasShield: false,
    tileEdges: [Feature.FIELD, Feature.FIELD, Feature.FIELD, Feature.ROAD],
    tileCenter: Feature.MONASTERY,
    tileID: "40",
  },
  {
    id: "18",
    orientation: 0,
    hasShield: false,
    tileEdges: [Feature.ROAD, Feature.CITY, Feature.FIELD, Feature.ROAD],
    tileCenter: Feature.ROAD,
    tileID: "41",
  },
  {
    id: "18",
    orientation: 0,
    hasShield: false,
    tileEdges: [Feature.ROAD, Feature.CITY, Feature.FIELD, Feature.ROAD],
    tileCenter: Feature.ROAD,
    tileID: "42",
  },
  {
    id: "18",
    orientation: 0,
    hasShield: false,
    tileEdges: [Feature.ROAD, Feature.CITY, Feature.FIELD, Feature.ROAD],
    tileCenter: Feature.ROAD,
    tileID: "43",
  },
  {
    id: "19",
    orientation: 0,
    hasShield: false,
    tileEdges: [Feature.ROAD, Feature.CITY, Feature.ROAD, Feature.FIELD],
    tileCenter: Feature.ROAD,
    tileID: "44",
  },
  {
    id: "19",
    orientation: 0,
    hasShield: false,
    tileEdges: [Feature.ROAD, Feature.CITY, Feature.ROAD, Feature.FIELD],
    tileCenter: Feature.ROAD,
    tileID: "45",
  },
  {
    id: "19",
    orientation: 0,
    hasShield: false,
    tileEdges: [Feature.ROAD, Feature.CITY, Feature.ROAD, Feature.FIELD],
    tileCenter: Feature.ROAD,
    tileID: "46",
  },
  {
    id: "19",
    orientation: 0,
    hasShield: false,
    tileEdges: [Feature.ROAD, Feature.CITY, Feature.ROAD, Feature.FIELD],
    tileCenter: Feature.ROAD,
    tileID: "47",
  },
  {
    id: "20",
    orientation: 0,
    hasShield: false,
    tileEdges: [Feature.ROAD, Feature.CITY, Feature.ROAD, Feature.ROAD],
    tileCenter: Feature.ROAD_END,
    tileID: "48",
  },
  {
    id: "20",
    orientation: 0,
    hasShield: false,
    tileEdges: [Feature.ROAD, Feature.CITY, Feature.ROAD, Feature.ROAD],
    tileCenter: Feature.ROAD_END,
    tileID: "49",
  },
  {
    id: "20",
    orientation: 0,
    hasShield: false,
    tileEdges: [Feature.ROAD, Feature.CITY, Feature.ROAD, Feature.ROAD],
    tileCenter: Feature.ROAD_END,
    tileID: "50",
  },
  {
    id: "21",
    orientation: 0,
    hasShield: false,
    tileEdges: [Feature.ROAD, Feature.FIELD, Feature.FIELD, Feature.ROAD],
    tileCenter: Feature.ROAD,
    tileID: "51",
  },
  {
    id: "21",
    orientation: 0,
    hasShield: false,
    tileEdges: [Feature.ROAD, Feature.FIELD, Feature.FIELD, Feature.ROAD],
    tileCenter: Feature.ROAD,
    tileID: "52",
  },
  {
    id: "21",
    orientation: 0,
    hasShield: false,
    tileEdges: [Feature.ROAD, Feature.FIELD, Feature.FIELD, Feature.ROAD],
    tileCenter: Feature.ROAD,
    tileID: "53",
  },
  {
    id: "21",
    orientation: 0,
    hasShield: false,
    tileEdges: [Feature.ROAD, Feature.FIELD, Feature.FIELD, Feature.ROAD],
    tileCenter: Feature.ROAD,
    tileID: "54",
  },
  {
    id: "21",
    orientation: 0,
    hasShield: false,
    tileEdges: [Feature.ROAD, Feature.FIELD, Feature.FIELD, Feature.ROAD],
    tileCenter: Feature.ROAD,
    tileID: "55",
  },
  {
    id: "21",
    orientation: 0,
    hasShield: false,
    tileEdges: [Feature.ROAD, Feature.FIELD, Feature.FIELD, Feature.ROAD],
    tileCenter: Feature.ROAD,
    tileID: "56",
  },
  {
    id: "21",
    orientation: 0,
    hasShield: false,
    tileEdges: [Feature.ROAD, Feature.FIELD, Feature.FIELD, Feature.ROAD],
    tileCenter: Feature.ROAD,
    tileID: "57",
  },
  {
    id: "21",
    orientation: 0,
    hasShield: false,
    tileEdges: [Feature.ROAD, Feature.FIELD, Feature.FIELD, Feature.ROAD],
    tileCenter: Feature.ROAD,
    tileID: "58",
  },
  {
    id: "21",
    orientation: 0,
    hasShield: false,
    tileEdges: [Feature.ROAD, Feature.FIELD, Feature.FIELD, Feature.ROAD],
    tileCenter: Feature.ROAD,
    tileID: "59",
  },
  {
    id: "22",
    orientation: 0,
    hasShield: false,
    tileEdges: [Feature.ROAD, Feature.FIELD, Feature.ROAD, Feature.FIELD],
    tileCenter: Feature.ROAD,
    tileID: "60",
  },
  {
    id: "22",
    orientation: 0,
    hasShield: false,
    tileEdges: [Feature.ROAD, Feature.FIELD, Feature.ROAD, Feature.FIELD],
    tileCenter: Feature.ROAD,
    tileID: "61",
  },
  {
    id: "22",
    orientation: 0,
    hasShield: false,
    tileEdges: [Feature.ROAD, Feature.FIELD, Feature.ROAD, Feature.FIELD],
    tileCenter: Feature.ROAD,
    tileID: "62",
  },
  {
    id: "22",
    orientation: 0,
    hasShield: false,
    tileEdges: [Feature.ROAD, Feature.FIELD, Feature.ROAD, Feature.FIELD],
    tileCenter: Feature.ROAD,
    tileID: "63",
  },
  {
    id: "22",
    orientation: 0,
    hasShield: false,
    tileEdges: [Feature.ROAD, Feature.FIELD, Feature.ROAD, Feature.FIELD],
    tileCenter: Feature.ROAD,
    tileID: "64",
  },
  {
    id: "22",
    orientation: 0,
    hasShield: false,
    tileEdges: [Feature.ROAD, Feature.FIELD, Feature.ROAD, Feature.FIELD],
    tileCenter: Feature.ROAD,
    tileID: "65",
  },
  {
    id: "22",
    orientation: 0,
    hasShield: false,
    tileEdges: [Feature.ROAD, Feature.FIELD, Feature.ROAD, Feature.FIELD],
    tileCenter: Feature.ROAD,
    tileID: "66",
  },
  {
    id: "22",
    orientation: 0,
    hasShield: false,
    tileEdges: [Feature.ROAD, Feature.FIELD, Feature.ROAD, Feature.FIELD],
    tileCenter: Feature.ROAD,
    tileID: "67",
  },
  {
    id: "23",
    orientation: 0,
    hasShield: false,
    tileEdges: [Feature.ROAD, Feature.FIELD, Feature.ROAD, Feature.ROAD],
    tileCenter: Feature.ROAD_END,
    tileID: "68",
  },
  {
    id: "23",
    orientation: 0,
    hasShield: false,
    tileEdges: [Feature.ROAD, Feature.FIELD, Feature.ROAD, Feature.ROAD],
    tileCenter: Feature.ROAD_END,
    tileID: "69",
  },
  {
    id: "23",
    orientation: 0,
    hasShield: false,
    tileEdges: [Feature.ROAD, Feature.FIELD, Feature.ROAD, Feature.ROAD],
    tileCenter: Feature.ROAD_END,
    tileID: "70",
  },
  {
    id: "23",
    orientation: 0,
    hasShield: false,
    tileEdges: [Feature.ROAD, Feature.FIELD, Feature.ROAD, Feature.ROAD],
    tileCenter: Feature.ROAD_END,
    tileID: "71",
  },
  {
    id: "24",
    orientation: 0,
    hasShield: false,
    tileEdges: [Feature.ROAD, Feature.ROAD, Feature.ROAD, Feature.ROAD],
    tileCenter: Feature.ROAD_END,
    tileID: "72",
  },
];
